## Projeto de Machine Learning
### Dados na educação através do repositório de dados da LOP


In [ ]:
import numpy as np
import pandas as pd

lista1e10 = pd.read_csv('/content/drive/MyDrive/Projeto_Machine_Learning_Education/DadosLop.csv')
lista1e10.head()



class_id                               user_id  \
0  09a04bfb-2d22-4009-a087-e29bd994207d  01466b70-43f4-45d9-81cb-72a3cc2ae4a7   
1  09a04bfb-2d22-4009-a087-e29bd994207d  0316f094-828f-4450-97ed-8276297c5a15   
2  09a04bfb-2d22-4009-a087-e29bd994207d  036ac739-1ff1-49ab-8869-45fe6187f19b   
3  09a04bfb-2d22-4009-a087-e29bd994207d  09d41d2d-e922-4981-a96a-c1e63527b00d   
4  09a04bfb-2d22-4009-a087-e29bd994207d  0bfb03fd-acf0-4fbe-a6f7-c955cae243d8   

   qtdList  percentList  medialist  aprovado  ateLista  totalErrorL01  \
0     12.0     0.800000  62.619048       1.0        13           29.0   
1      6.0     0.400000  37.222222       0.0         5           12.0   
2      1.0     0.066667   5.333333       0.0         0           13.0   
3     12.0     0.800000  80.000000       1.0        13           42.0   
4     11.0     0.733333  73.333333       1.0        12           36.0   

   totalAcertL01  acert_100L01  total_submL01  totalQuestL01  subm/questL01  \
0            7.0           7.0           36.0            5.0            7.2   
1            9.0           9.0           21.0            5.0            4.2   
2            4.0           4.0           17.0            5.0            3.4   
3            6.0           6.0           48.0            5.0            9.6   
4            5.0           5.0           41.0            5.0            8.2   

   timeInSecoundsL01  submeteuL01  aprovadoLista01  medialist01  \
0            21832.0          1.0              1.0        100.0   
1             4765.0          1.0              1.0        100.0   
2            30318.0          1.0              1.0         80.0   
3           119316.0          1.0              1.0        100.0   
4            43176.0          1.0              1.0        100.0   

   percentErrorL01  percentAcertL01  percentAcert100L01  time/submL01  \
0         0.805556         0.194444            0.194444    606.444444   
1         0.571429         0.428571            0.428571    226.904762   
2         0.764706         0.235294            0.235294   1783.411765   
3         0.875000         0.125000            0.125000   2485.750000   
4         0.878049         0.121951            0.121951   1053.073171   

   aprovadoLista10  medialist10  totalErrorL10  totalAcertL10  acert_100lL0  \
0              0.0         25.0            5.0            1.0           1.0   
1              0.0          0.0            0.0            0.0           0.0   
2              0.0          0.0            0.0            0.0           0.0   
3              1.0        100.0           82.0           19.0           6.0   
4              1.0        100.0           17.0            5.0           5.0   

   total_submlL0  totalQuestL10  subm/questL10  timeInSecoundsL10  \
0            6.0            1.0           6.00             3929.0   
1            0.0            0.0           0.00                0.0   
2            0.0            0.0           0.00                0.0   
3          101.0            4.0          25.25           601865.0   
4           22.0            4.0           5.50            11105.0   

   submeteuL10  percentErrorL10  percentAcertL10  percentAcert100L10  \
0          1.0         0.833333         0.166667            0.166667   
1          0.0         0.000000         0.000000            0.000000   
2          0.0         0.000000         0.000000            0.000000   
3          1.0         0.811881         0.188119            0.059406   
4          1.0         0.772727         0.227273            0.227273   

   time/submL10  
0    654.833333  
1      0.000000  
2      0.000000  
3   5959.059406  
4    504.772727

In [ ]:
lista2 = pd.read_csv('/content/drive/MyDrive/Projeto_Machine_Learning_Education/lista02.csv')
lista2.head()

class_id                               user_id  \
0  09a04bfb-2d22-4009-a087-e29bd994207d  01466b70-43f4-45d9-81cb-72a3cc2ae4a7   
1  09a04bfb-2d22-4009-a087-e29bd994207d  0316f094-828f-4450-97ed-8276297c5a15   
2  09a04bfb-2d22-4009-a087-e29bd994207d  09d41d2d-e922-4981-a96a-c1e63527b00d   
3  09a04bfb-2d22-4009-a087-e29bd994207d  0bfb03fd-acf0-4fbe-a6f7-c955cae243d8   
4  09a04bfb-2d22-4009-a087-e29bd994207d  0def740e-cdac-4347-8af1-12c29f3000b0   

   totalError  totalAcert  acert_100  total_subm  totalQuest  subm/quest  \
0        65.0        23.0       23.0        88.0        10.0    8.800000   
1        15.0        10.0       10.0        25.0        10.0    2.500000   
2        11.0        12.0       12.0        23.0        10.0    2.300000   
3        14.0        13.0       11.0        27.0        10.0    2.700000   
4        24.0         9.0        9.0        33.0         9.0    3.666667   

   timeInSecounds  qtdList  percentList  aprovadoLista10  medialist10  \
0         58174.0     12.0     0.800000                1        100.0   
1          7951.0      6.0     0.400000                1        100.0   
2          8705.0     12.0     0.800000                1        100.0   
3         15394.0     11.0     0.733333                1        100.0   
4         12167.0      3.0     0.200000                1         90.0   

   medialist  aprovado  ateLista  submeteu  percentError  percentAcert  \
0  62.619048       1.0        13         1      0.738636      0.261364   
1  37.222222       0.0         5         1      0.600000      0.400000   
2  80.000000       1.0        13         1      0.478261      0.521739   
3  73.333333       1.0        12         1      0.518519      0.481481   
4  13.619048       0.0         3         1      0.727273      0.272727   

   percentAcert100   time/subm  
0         0.261364  661.068182  
1         0.400000  318.040000  
2         0.521739  378.478261  
3         0.407407  570.148148  
4         0.272727  368.696970

In [ ]:
dataset = pd.merge(lista1e10,lista2,how='outer')
dataset.head()

class_id                               user_id  \
0  09a04bfb-2d22-4009-a087-e29bd994207d  01466b70-43f4-45d9-81cb-72a3cc2ae4a7   
1  09a04bfb-2d22-4009-a087-e29bd994207d  0316f094-828f-4450-97ed-8276297c5a15   
2  09a04bfb-2d22-4009-a087-e29bd994207d  036ac739-1ff1-49ab-8869-45fe6187f19b   
3  09a04bfb-2d22-4009-a087-e29bd994207d  09d41d2d-e922-4981-a96a-c1e63527b00d   
4  09a04bfb-2d22-4009-a087-e29bd994207d  0bfb03fd-acf0-4fbe-a6f7-c955cae243d8   

   qtdList  percentList  medialist  aprovado  ateLista  totalErrorL01  \
0     12.0     0.800000  62.619048       1.0        13           29.0   
1      6.0     0.400000  37.222222       0.0         5           12.0   
2      1.0     0.066667   5.333333       0.0         0           13.0   
3     12.0     0.800000  80.000000       1.0        13           42.0   
4     11.0     0.733333  73.333333       1.0        12           36.0   

   totalAcertL01  acert_100L01  total_submL01  totalQuestL01  subm/questL01  \
0            7.0           7.0           36.0            5.0            7.2   
1            9.0           9.0           21.0            5.0            4.2   
2            4.0           4.0           17.0            5.0            3.4   
3            6.0           6.0           48.0            5.0            9.6   
4            5.0           5.0           41.0            5.0            8.2   

   timeInSecoundsL01  submeteuL01  aprovadoLista01  medialist01  \
0            21832.0          1.0              1.0        100.0   
1             4765.0          1.0              1.0        100.0   
2            30318.0          1.0              1.0         80.0   
3           119316.0          1.0              1.0        100.0   
4            43176.0          1.0              1.0        100.0   

   percentErrorL01  percentAcertL01  percentAcert100L01  time/submL01  \
0         0.805556         0.194444            0.194444    606.444444   
1         0.571429         0.428571            0.428571    226.904762   
2         0.764706         0.235294            0.235294   1783.411765   
3         0.875000         0.125000            0.125000   2485.750000   
4         0.878049         0.121951            0.121951   1053.073171   

   aprovadoLista10  medialist10  totalErrorL10  totalAcertL10  acert_100lL0  \
0              0.0         25.0            5.0            1.0           1.0   
1              0.0          0.0            0.0            0.0           0.0   
2              0.0          0.0            0.0            0.0           0.0   
3              1.0        100.0           82.0           19.0           6.0   
4              1.0        100.0           17.0            5.0           5.0   

   total_submlL0  totalQuestL10  subm/questL10  timeInSecoundsL10  \
0            6.0            1.0           6.00             3929.0   
1            0.0            0.0           0.00                0.0   
2            0.0            0.0           0.00                0.0   
3          101.0            4.0          25.25           601865.0   
4           22.0            4.0           5.50            11105.0   

   submeteuL10  percentErrorL10  percentAcertL10  percentAcert100L10  \
0          1.0         0.833333         0.166667            0.166667   
1          0.0         0.000000         0.000000            0.000000   
2          0.0         0.000000         0.000000            0.000000   
3          1.0         0.811881         0.188119            0.059406   
4          1.0         0.772727         0.227273            0.227273   

   time/submL10  totalError  totalAcert  acert_100  total_subm  totalQuest  \
0    654.833333         NaN         NaN        NaN         NaN         NaN   
1      0.000000         NaN         NaN        NaN         NaN         NaN   
2      0.000000         0.0         0.0        0.0         0.0         0.0   
3   5959.059406        11.0        12.0       12.0        23.0        10.0   
4    504.772727        14.0        13.0       11.0        27.0        10.0 

In [ ]:
display(dataset)

class_id  \
0     09a04bfb-2d22-4009-a087-e29bd994207d   
1     09a04bfb-2d22-4009-a087-e29bd994207d   
2     09a04bfb-2d22-4009-a087-e29bd994207d   
3     09a04bfb-2d22-4009-a087-e29bd994207d   
4     09a04bfb-2d22-4009-a087-e29bd994207d   
...                                    ...   
1116  86e0792a-87df-4db4-9040-bc94ef539825   
1117  1fd9fe78-b7d0-4d90-b35e-775851ea1416   
1118  77335557-c5d1-4144-be6e-84b6114ec22e   
1119  1fd9fe78-b7d0-4d90-b35e-775851ea1416   
1120  8f055c33-00ad-4284-aec8-da401901e795   

                                   user_id  qtdList  percentList  medialist  \
0     01466b70-43f4-45d9-81cb-72a3cc2ae4a7     12.0     0.800000  62.619048   
1     0316f094-828f-4450-97ed-8276297c5a15      6.0     0.400000  37.222222   
2     036ac739-1ff1-49ab-8869-45fe6187f19b      1.0     0.066667   5.333333   
3     09d41d2d-e922-4981-a96a-c1e63527b00d     12.0     0.800000  80.000000   
4     0bfb03fd-acf0-4fbe-a6f7-c955cae243d8     11.0     0.733333  73.333333   
...                                    ...      ...          ...        ...   
1116  f60da29b-9a17-4668-979d-cdfa6638b2ff      8.0     0.533333  53.333333   
1117  5dac7fa0-1127-4746-8305-52ce7c3e5f08     14.0     0.933333  87.611111   
1118  650f563b-c6e9-4406-9053-218f2ebd2153      2.0     0.133333   3.333333   
1119  3ec13f7d-11e2-4854-9e52-b4a38f183cf2      6.0     0.400000  29.055556   
1120  52c0d652-4237-4593-bc6f-b4246fa30850      5.0     0.333333  24.055556   

      aprovado  ateLista  totalErrorL01  totalAcertL01  acert_100L01  \
0          1.0        13           29.0            7.0           7.0   
1          0.0         5           12.0            9.0           9.0   
2          0.0         0           13.0            4.0           4.0   
3          1.0        13           42.0            6.0           6.0   
4          1.0        12           36.0            5.0           5.0   
...        ...       ...            ...            ...           ...   
1116       1.0        14            NaN            NaN           NaN   
1117       1.0        14            NaN            NaN           NaN   
1118       0.0         9            NaN            NaN           NaN   
1119       0.0        12            NaN            NaN           NaN   
1120       0.0        11            NaN            NaN           NaN   

      total_submL01  totalQuestL01  subm/questL01  timeInSecoundsL01  \
0              36.0            5.0            7.2            21832.0   
1              21.0            5.0            4.2             4765.0   
2              17.0            5.0            3.4            30318.0   
3              48.0            5.0            9.6           119316.0   
4              41.0            5.0            8.2            43176.0   
...             ...            ...            ...                ...   
1116            NaN            NaN            NaN                NaN   
1117            NaN            NaN            NaN                NaN   
1118            NaN            NaN            NaN                NaN   
1119            NaN            NaN            NaN                NaN   
1120            NaN            NaN            NaN                NaN   

      submeteuL01  aprovadoLista01  medialist01  percentErrorL01  \
0             1.0              1.0        100.0         0.805556   
1             1.0              1.0        100.0         0.571429   
2             1.0              1.0         80.0         0.764706   
3             1.0              1.0        100.0         0.875000   
4             1.0              1.0        100.0         0.878049   
...           ...              ...          ...              ...   
1116          NaN              NaN          NaN              NaN   
1117          NaN              NaN          NaN              NaN   
1118          NaN              NaN          NaN              NaN   
1119          NaN              NaN          NaN              NaN   
1120          NaN              NaN          NaN       

In [ ]:
pd.set_option('display.max_columns', None)
dataset
data = dataset.dropna()
print(data)

                                 class_id  \
2    09a04bfb-2d22-4009-a087-e29bd994207d   
3    09a04bfb-2d22-4009-a087-e29bd994207d   
4    09a04bfb-2d22-4009-a087-e29bd994207d   
6    09a04bfb-2d22-4009-a087-e29bd994207d   
11   09a04bfb-2d22-4009-a087-e29bd994207d   
..                                    ...   
810  1fd9fe78-b7d0-4d90-b35e-775851ea1416   
811  77335557-c5d1-4144-be6e-84b6114ec22e   
814  1fd9fe78-b7d0-4d90-b35e-775851ea1416   
816  09a04bfb-2d22-4009-a087-e29bd994207d   
817  f7144f91-f493-4e55-aac5-39f0d4add995   

                                  user_id  qtdList  percentList  medialist  \
2    036ac739-1ff1-49ab-8869-45fe6187f19b      1.0     0.066667   5.333333   
3    09d41d2d-e922-4981-a96a-c1e63527b00d     12.0     0.800000  80.000000   
4    0bfb03fd-acf0-4fbe-a6f7-c955cae243d8     11.0     0.733333  73.333333   
6    0f434da0-fdef-4a5a-b87c-2eee5711c750     12.0     0.800000  79.166667   
11   1b04ab8c-4261-4ce4-a449-36e1d1f61727     15.0     1.000000  95.2

### Selecionando na coluna submeteuL01 os valores igual a zero

In [ ]:
coluna_selecionada = data.loc[data['submeteuL10'] == 0,:]
coluna_selecionada1 = data.loc[data['submeteuL10'] == 1,'submeteuL10']
print(len(data['submeteuL10']))
quantidade_1 = len(coluna_selecionada1)
print("quantidade de submissões lista igual a  1",quantidade_1)

quantidade = len(coluna_selecionada)
print("quantidade de submissoes da lista 1 igual a 0",quantidade)
print(coluna_selecionada)

510
quantidade de submissões lista igual a  1 412
quantidade de submissoes da lista 1 igual a 0 98
                                 class_id  \
2    09a04bfb-2d22-4009-a087-e29bd994207d   
26   09a04bfb-2d22-4009-a087-e29bd994207d   
27   09a04bfb-2d22-4009-a087-e29bd994207d   
116  09a04bfb-2d22-4009-a087-e29bd994207d   
139  1fd9fe78-b7d0-4d90-b35e-775851ea1416   
..                                    ...   
810  1fd9fe78-b7d0-4d90-b35e-775851ea1416   
811  77335557-c5d1-4144-be6e-84b6114ec22e   
814  1fd9fe78-b7d0-4d90-b35e-775851ea1416   
816  09a04bfb-2d22-4009-a087-e29bd994207d   
817  f7144f91-f493-4e55-aac5-39f0d4add995   

                                  user_id  qtdList  percentList  medialist  \
2    036ac739-1ff1-49ab-8869-45fe6187f19b      1.0     0.066667   5.333333   
26   45772c10-e6ce-44ec-ae4d-dde2d8a4f826      6.0     0.400000  33.333333   
27   49f6ca0d-8849-4c4d-9237-60c19dcb1c7b      4.0     0.266667   3.821159   
116  f39a610a-85e9-43cf-a5d0-163a5e9e2a9b      1

### Equilibrando a rede



In [ ]:
valores_sorteados = coluna_selecionada.sample(n=98*3, replace=True)
print(valores_sorteados)

                                 class_id  \
791  86e0792a-87df-4db4-9040-bc94ef539825   
785  d99923f0-d174-4902-9759-c8220b821d36   
796  f7144f91-f493-4e55-aac5-39f0d4add995   
763  8f055c33-00ad-4284-aec8-da401901e795   
807  09a04bfb-2d22-4009-a087-e29bd994207d   
..                                    ...   
756  1fd9fe78-b7d0-4d90-b35e-775851ea1416   
780  d99923f0-d174-4902-9759-c8220b821d36   
816  09a04bfb-2d22-4009-a087-e29bd994207d   
379  86e0792a-87df-4db4-9040-bc94ef539825   
187  1fd9fe78-b7d0-4d90-b35e-775851ea1416   

                                  user_id  qtdList  percentList  medialist  \
791  d51ff793-7a71-42f7-86c6-eea9ede6ac47      0.0     0.000000   0.000000   
785  25ca7cc6-dd6c-4af3-a6b8-d682fdcda6b1      0.0     0.000000   0.000000   
796  2279a3d1-56a6-4633-8991-ce9faa711044      0.0     0.000000   0.000000   
763  74fa3d78-2680-4862-a43d-a1870472892a      0.0     0.000000   0.000000   
807  4aae5ff5-5eac-4c94-9bee-6101388969dd      0.0     0.000000   0.0

### Concatenando os valores


In [ ]:
todos = pd.concat([data, valores_sorteados], ignore_index=True)
print(todos)
print(todos['submeteuL10'])

                                 class_id  \
0    09a04bfb-2d22-4009-a087-e29bd994207d   
1    09a04bfb-2d22-4009-a087-e29bd994207d   
2    09a04bfb-2d22-4009-a087-e29bd994207d   
3    09a04bfb-2d22-4009-a087-e29bd994207d   
4    09a04bfb-2d22-4009-a087-e29bd994207d   
..                                    ...   
799  1fd9fe78-b7d0-4d90-b35e-775851ea1416   
800  d99923f0-d174-4902-9759-c8220b821d36   
801  09a04bfb-2d22-4009-a087-e29bd994207d   
802  86e0792a-87df-4db4-9040-bc94ef539825   
803  1fd9fe78-b7d0-4d90-b35e-775851ea1416   

                                  user_id  qtdList  percentList  medialist  \
0    036ac739-1ff1-49ab-8869-45fe6187f19b      1.0     0.066667   5.333333   
1    09d41d2d-e922-4981-a96a-c1e63527b00d     12.0     0.800000  80.000000   
2    0bfb03fd-acf0-4fbe-a6f7-c955cae243d8     11.0     0.733333  73.333333   
3    0f434da0-fdef-4a5a-b87c-2eee5711c750     12.0     0.800000  79.166667   
4    1b04ab8c-4261-4ce4-a449-36e1d1f61727     15.0     1.000000  95.2

In [ ]:
todos_selecionada = todos.loc[todos['submeteuL10'] == 0,:]
todos_selecionada1 = todos.loc[todos['submeteuL10'] == 1,:]
print(len(todos['submeteuL10']))
print(todos_selecionada.shape)
print(todos_selecionada1.shape)
todos.head()

804
(392, 47)
(412, 47)


class_id                               user_id  \
0  09a04bfb-2d22-4009-a087-e29bd994207d  036ac739-1ff1-49ab-8869-45fe6187f19b   
1  09a04bfb-2d22-4009-a087-e29bd994207d  09d41d2d-e922-4981-a96a-c1e63527b00d   
2  09a04bfb-2d22-4009-a087-e29bd994207d  0bfb03fd-acf0-4fbe-a6f7-c955cae243d8   
3  09a04bfb-2d22-4009-a087-e29bd994207d  0f434da0-fdef-4a5a-b87c-2eee5711c750   
4  09a04bfb-2d22-4009-a087-e29bd994207d  1b04ab8c-4261-4ce4-a449-36e1d1f61727   

   qtdList  percentList  medialist  aprovado  ateLista  totalErrorL01  \
0      1.0     0.066667   5.333333       0.0         0           13.0   
1     12.0     0.800000  80.000000       1.0        13           42.0   
2     11.0     0.733333  73.333333       1.0        12           36.0   
3     12.0     0.800000  79.166667       1.0        13            2.0   
4     15.0     1.000000  95.238095       1.0        14           24.0   

   totalAcertL01  acert_100L01  total_submL01  totalQuestL01  subm/questL01  \
0            4.0           4.0           17.0            5.0            3.4   
1            6.0           6.0           48.0            5.0            9.6   
2            5.0           5.0           41.0            5.0            8.2   
3            8.0           8.0           10.0            5.0            2.0   
4           31.0          31.0           55.0            5.0           11.0   

   timeInSecoundsL01  submeteuL01  aprovadoLista01  medialist01  \
0            30318.0          1.0              1.0         80.0   
1           119316.0          1.0              1.0        100.0   
2            43176.0          1.0              1.0        100.0   
3             3401.0          1.0              1.0        100.0   
4            53970.0          1.0              1.0        100.0   

   percentErrorL01  percentAcertL01  percentAcert100L01  time/submL01  \
0         0.764706         0.235294            0.235294   1783.411765   
1         0.875000         0.125000            0.125000   2485.750000   
2         0.878049         0.121951            0.121951   1053.073171   
3         0.200000         0.800000            0.800000    340.100000   
4         0.436364         0.563636            0.563636    981.272727   

   aprovadoLista10  medialist10  totalErrorL10  totalAcertL10  acert_100lL0  \
0              0.0          0.0            0.0            0.0           0.0   
1              1.0        100.0           82.0           19.0           6.0   
2              1.0        100.0           17.0            5.0           5.0   
3              1.0        100.0           13.0            4.0           4.0   
4              1.0        100.0           12.0            5.0           5.0   

   total_submlL0  totalQuestL10  subm/questL10  timeInSecoundsL10  \
0            0.0            0.0           0.00                0.0   
1          101.0            4.0          25.25           601865.0   
2           22.0            4.0           5.50            11105.0   
3           17.0            4.0           4.25            75739.0   
4           17.0            4.0           4.25             8905.0   

   submeteuL10  percentErrorL10  percentAcertL10  percentAcert100L10  \
0          0.0         0.000000         0.000000            0.000000   
1          1.0         0.811881         0.188119            0.059406   
2          1.0         0.772727         0.227273            0.227273   
3          1.0         0.764706         0.235294            0.235294   
4          1.0         0.705882         0.294118            0.294118   

   time/submL10  totalError  totalAcert  acert_100  total_subm  totalQuest  \
0      0.000000         0.0         0.0        0.0         0.0         0.0   
1   5959.059406        11.0        12.0       12.0        23.0        10.0   
2    504.772727        14.0        13.0       11.0        27.0        10.0   
3   4455.235294        57.0        19.0       19.0        76.0        10.0   
4    523.823529        23.0        24.0       24.0        47.0        10.0 

In [ ]:
x = todos.loc[:,['totalAcertL01','aprovadoLista01','subm/questL01','timeInSecoundsL01','time/submL01']].values
y = todos['submeteuL10'].values

print(x)
print(y)

[[4.00000000e+00 1.00000000e+00 3.40000000e+00 3.03180000e+04
  1.78341176e+03]
 [6.00000000e+00 1.00000000e+00 9.60000000e+00 1.19316000e+05
  2.48575000e+03]
 [5.00000000e+00 1.00000000e+00 8.20000000e+00 4.31760000e+04
  1.05307317e+03]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [5.00000000e+00 1.00000000e+00 4.60000000e+00 1.04330000e+04
  4.53608696e+02]
 [2.00000000e+00 0.00000000e+00 2.20000000e+01 6.48620000e+04
  1.47413636e+03]]
[0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1.
 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1.

### Normalização


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

### Normalização

In [ ]:
from sklearn.preprocessing import MinMaxScaler
print(X_train[0:5])
sc = MinMaxScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)
print(X_train[0:5])

[[1.10000000e+01 1.00000000e+00 4.60000000e+00 1.85310000e+04
  8.05695652e+02]
 [1.00000000e+00 0.00000000e+00 1.00000000e+00 7.60000000e+01
  7.60000000e+01]
 [6.00000000e+00 1.00000000e+00 5.60000000e+00 1.48160000e+04
  5.29142857e+02]
 [6.00000000e+00 1.00000000e+00 4.40000000e+00 1.50560000e+04
  6.84363636e+02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]]
[[0.2972973  1.         0.11330049 0.01984558 0.07093297]
 [0.02702703 0.         0.02463054 0.00213608 0.01697565]
 [0.16216216 1.         0.13793103 0.01628065 0.05048328]
 [0.16216216 1.         0.10837438 0.01651095 0.06196108]
 [0.         0.         0.         0.00206315 0.01135583]]


### Treinamento com os valores da tebela correlacinando os acertos, o tempo de submissao, a quantidade de listas submetidas e

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel='rbf', random_state=1, gamma=2, C=40)
classifier.fit(X_train, y_train)

SVC(C=40, gamma=2, random_state=1)

### Avaliação do modelo de decisão

In [ ]:
y_pred = classifier.predict(X_test)

print(y_test[0:])
print(y_pred[0:])

[1. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 1. 1. 0. 0. 1. 1. 0. 0. 1. 0. 1. 1. 0.
 1. 1. 0. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 1. 1. 0. 1. 1. 0. 0. 1. 1. 1. 0.
 1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1. 0. 1. 0. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0.
 1. 0. 0. 1. 0. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 0. 1. 1. 1.
 0. 1. 0. 1. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1.
 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 0. 1. 0.
 1. 0. 1. 1. 1. 0. 0. 0. 1. 1. 1. 0. 0. 1. 0. 1. 0.]
[1. 0. 1. 1. 0. 1. 1. 0. 0. 0. 1. 1. 1. 0. 0. 1. 1. 0. 0. 1. 0. 1. 1. 0.
 1. 1. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 1. 1. 0. 0. 1. 1. 1. 0.
 1. 1. 0. 1. 0. 0. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 0. 0. 0.
 1. 0. 0. 1. 0. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 0. 1. 1. 1.
 0. 1. 0. 1. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 1. 0. 1. 1. 1. 1. 0. 1. 1.
 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 0. 1. 0.
 1. 1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 0. 0. 1. 0. 1. 0.]


In [ ]:
from sklearn.metrics import accuracy_score

print("Acurácia: ", accuracy_score(y_test,y_pred)*100, "%"  )

Acurácia:  95.03105590062113 %


### O balanço médio da acurácia


In [ ]:
from sklearn.metrics import balanced_accuracy_score
bc = balanced_accuracy_score(y_test, y_pred)
print(bc*100)

94.87179487179486


### Matriz de confusão


In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("Matrix de confusão: ")
print(cm)

Matrix de confusão: 
[[70  8]
 [ 0 83]]


In [ ]:
print(cm[0,0])
print(cm[1,0])


70
0


### Precisão do modelo

In [ ]:
from sklearn.metrics import precision_score
pr = precision_score(y_test,y_pred,average='macro')
print("A precisão do modelo é ",pr*100)

A precisão do modelo é  95.60439560439559


In [ ]:
from sklearn.metrics import recall_score
rec = recall_score(y_test,y_pred)
print(rec)

1.0
